### ISSUE TITLE
Request: add a license

### ISSUE THREAD

**Issue by c-kirkeby** [Flipping-Utilities/osrs-datasets#8]
Would you consider adding a permissive license to use the data in this repo?

**Comment by AntonyGarand** [comment]
Hey!
Most of the data in this repo is only parsed from the osrs wiki / game, which is under this license:
Content on this site is licensed under [CC BY-NC-SA 3.0](https://creativecommons.org/licenses/by-nc-sa/3.0/); [additional terms apply](https://meta.weirdgloop.org/w/Project:Copyrights).

You'll likely prefer the [parsed-osrs](https://github.com/Flipping-Utilities/parsed-osrs) project though, on which the code is unlicensed atm (but feel free to consider it MIT licensed, it's available for free to all), and the content following the same CC as the wiki due to being scraped from their site.
